root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/main ./cmd/api"
bin = "tmp/main"
full_bin = "tmp/main"  
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "node_modules"]
delay = 1000
stop_on_error = true

[log]
time = true
